### ISSUE TITLE
Question about mutux example

### ISSUE THREAD

**Issue by techotron** [plagioriginal/concurrency-in-go#1]
In the mutux example `value` is incremented but I'm confused where this variable has come from (perhaps it's implied but I've missed it?).

```
func (c *ConcurrentCounter) Increment() {
	c.mu.Lock() // restricts the memory pointers here. Guarantees only one write to value.
	value++
	c.mu.Unlock() // Being called with defer is also nice.
}
```

What _would_ make sense to me would be if it was `c.value++`

**Comment by joaocgduarte** [comment]
Hi,

Yes, you are right. This is bound to have typos and errors like this. I'll try to fix it as soon as I have time. If you want, you can try to open a pull request and make changes

Thanks!

**Comment by joaocgduarte** [comment]
Fixed :) If you find more of these, feel free to let me know.

Thanks.
